services:
  fetcher:
    container_name: fetcher
    restart: on-failure:10
    image: ghcr.io/containerman17/frostbyte:latest
    volumes:
      - ./plugins:/plugins
      - ./data:/data
    environment:
      - ROLES=fetcher
    logging:
      driver: "json-file"
      options:
        max-size: "150m"
        max-file: "5" 
  api:
    container_name: api
    restart: on-failure:10
    image: ghcr.io/containerman17/frostbyte:latest
    volumes:
      - ./plugins:/plugins
      - ./data:/data
      - ./frontend/dist:/assets
    environment:
      - PORT=80
      - ROLES=api
      - ASSETS_DIR=/assets
    ports:
      - 80:80
    logging:
      driver: "json-file"
      options:
        max-size: "150m"
        max-file: "5" 
  indexer:
    container_name: indexer
    restart: on-failure:10
    image: ghcr.io/containerman17/frostbyte:latest
    volumes:
      - ./plugins:/plugins
      - ./data:/data
    environment:
      - ROLES=indexer
    logging:
      driver: "json-file"
      options:
        max-size: "150m"
        max-file: "5"
  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ~/certs/cloudflare-origin.pem:/etc/nginx/certs/cloudflare-origin.pem:ro
      - ~/certs/cloudflare-origin.key:/etc/nginx/certs/cloudflare-origin.key:ro
      - ~/certs/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
